# This rule is not used by the project cmstate-injector-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the cache.spicedelver.me.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cmstate-injector-operator
    app.kubernetes.io/managed-by: kustomize
  name: cmstate-editor-role
rules:
- apiGroups:
  - cache.spicedelver.me
  resources:
  - cmstates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.spicedelver.me
  resources:
  - cmstates/status
  verbs:
  - get
