# This rule is not used by the project cmstate-injector-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to cache.spicedelver.me resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cmstate-injector-operator
    app.kubernetes.io/managed-by: kustomize
  name: cmtemplate-viewer-role
rules:
- apiGroups:
  - cache.spicedelver.me
  resources:
  - cmtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.spicedelver.me
  resources:
  - cmtemplates/status
  verbs:
  - get
