---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.spicedelver.me
  resources:
  - cmstates
  - cmtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.spicedelver.me
  resources:
  - cmstates/finalizers
  - cmtemplates/finalizers
  verbs:
  - update
- apiGroups:
  - cache.spicedelver.me
  resources:
  - cmstates/status
  - cmtemplates/status
  verbs:
  - get
  - patch
  - update
